name: SonarQube Scan

on:
  push:
    branches:
      - main
      - 'feature/*'  # or any other branches you want to scan
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache SonarQube dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: |
            ${{ runner.os }}-sonar-cache

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.host.url=https://sonarqube.yourdomain.com \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
